# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podread < Formula
  desc "CLI for podread.app — text to speech to your personal podcast feed"
  homepage "https://podread.app"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v0.1.5/podread_darwin_amd64.tar.gz"
      sha256 "f74883fecea382d13280f3b37870cb1e45d9ca5c5b540f9b9b747f544e05099c"

      define_method(:install) do
        bin.install "podread"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v0.1.5/podread_darwin_arm64.tar.gz"
      sha256 "fa80c213cd14abc4467c4cd8d7de0fbc3371c9e89996e7a381c1eaf52c508ba2"

      define_method(:install) do
        bin.install "podread"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v0.1.5/podread_linux_amd64.tar.gz"
      sha256 "a0bf122266f2c96dbb40bd1822a451cf0212fdb27b2d8c9be43faefc60f8e485"
      define_method(:install) do
        bin.install "podread"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v0.1.5/podread_linux_arm64.tar.gz"
      sha256 "663757a99d8ddf06fc0f0a9dbbb63764df9d41de3fcbaf577656c757f8d3bf5a"
      define_method(:install) do
        bin.install "podread"
      end
    end
  end
end
