# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podread < Formula
  desc "CLI for podread.app — text to speech to your personal podcast feed"
  homepage "https://podread.app"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v0.1.3/podread_darwin_amd64.tar.gz"
      sha256 "d83131be1455c6edba3d41d341aa9f5b1a43a5cda779dfb3f694a0a8072b91df"

      define_method(:install) do
        bin.install "podread"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v0.1.3/podread_darwin_arm64.tar.gz"
      sha256 "b9fa0ad39adc12976193be4501802e71a890f8581d01000414a794650232ce56"

      define_method(:install) do
        bin.install "podread"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v0.1.3/podread_linux_amd64.tar.gz"
      sha256 "27dcbf6247832d568f23bd3fe302d2521ea1dde1aafdf70ea6bd769fbeca6dd5"
      define_method(:install) do
        bin.install "podread"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v0.1.3/podread_linux_arm64.tar.gz"
      sha256 "3df807370d6cb62348f4fd2d5721c1522d26d0c8f4ad10831c32a4d18332f791"
      define_method(:install) do
        bin.install "podread"
      end
    end
  end
end
