# This file was generated by GoReleaser. DO NOT EDIT.
cask "podread" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/podread"]
    end
  end

  version "0.1.9"

  on_macos do
    on_arm do
      sha256 "7798cbcbbd8584771c3f982541167153a16592f1da1ae1785262fa7fe8afcaf3"
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v#{version}/podread_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "47c4ada7791a2a22a6660f936ca16ee68229e6c611843044269277bc405d12c1"
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v#{version}/podread_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5fe2df30d22db459a4c4786126444cd220ea1fee79497f92ec2f47d7ea078487"
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v#{version}/podread_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6a28881305659aa9478b9dc22a9026bd20166de6d2c112b5a7d7d7850eb94228"
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v#{version}/podread_linux_amd64.tar.gz"
    end
  end

  name "podread"
  desc "CLI for podread.app - text to speech to your personal podcast feed"
  homepage "https://podread.app/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podread"

  # No zap stanza required
end
