# This file was generated by GoReleaser. DO NOT EDIT.
cask "podread" do
  version "0.1.8"

  on_macos do
    on_arm do
      sha256 "bfd85c9dfa7bca231414b87db12a4eaaffffd995249ee030dcb484d20c74a32e"
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v#{version}/podread_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5c02d78d23a623ad95814297adccf597339340cc77860b273aba8fb897b184cd"
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v#{version}/podread_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b59cb903a44886042be96a073e07b4e40b2395ceaee99bbff9725bd0a39b4f3f"
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v#{version}/podread_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7a046d4e9f88014d5f6e9ac8125d0a9ae8a6207aa72e6bace2250fa92d50537e"
      url "https://github.com/jesse-spevack/podread-cli/releases/download/v#{version}/podread_linux_amd64.tar.gz"
    end
  end

  name "podread"
  desc "CLI for podread.app - text to speech to your personal podcast feed"
  homepage "https://podread.app/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podread"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/podread"]
    end
  end

  # No zap stanza required
end
